---
- name: Epel repository
  yum:
    name: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ pip_epel_release }}.noarch.rpm"
    state: present
    update_cache: yes
  register: epel_repo

- name: Install {{ pip_package }}
  yum:
    name: "{{ pip_package }}"
    state: present
  register: pip_install
  when: epel_repo.rc is defined and epel_repo.rc == 0

- name: Upgrade Pip with {{ pip_bin }}
  shell: "{{ pip_bin }} install --upgrade pip"
  when: pip_install is changed

- name: Install all packages with {{ pip_bin }}
  pip:
    name: "{{ pip_install_packages }}"
    executable: "{{ pip_executable }}"
    state: present
  when: pip_install.rc is defined and pip_install.rc == 0