---
- name: Epel repository
  yum:
    name: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm"
    state: present
  register: epel_repo

- name: Update cache
  yum:
    name: "*"
    update_cache: yes
  when: epel_repo is changed

- name: Install packages
  yum:
    name: "{{ pip_package }}"
    state: present
  register: pip_install
  when: epel_repo.rc is defined and epel_repo.rc == 0

- name: Verify if pip was upgraded
  stat:
    path: "/usr/local/bin/{{ pip }}"
  register: pip_executable_path

- name: Upgrade {{ pip }}
  pip:
    name: pip
    state: present
    executable: "/usr/bin/{{ pip }}"
    extra_args: --upgrade
  register: pip_upgrade
  when: not pip_executable_path.stat.exists

- name: Clear cache
  shell: hash -r
  changed_when: pip_upgrade is changed

- name: Install all packages with {{ pip }}
  pip:
    name: "{{ pip_install_packages }}"
    state: present
    executable: "/usr/local/bin/{{ pip }}"
  when: pip_install.rc is defined and pip_install.rc == 0