---
- name: Update packages
  apt:
    name: "*"
    update_cache: yes

- name: Install packages
  yum:
    name: "{{ pip_package }}"
    state: present
  register: pip_install

- name: Verify if pip was upgraded
  stat:
    path: "/usr/local/bin/{{ pip }}"
  register: pip_executable_path

- name: Upgrade {{ pip }}
  pip:
    name: pip
    state: present
    executable: "/usr/bin/{{ pip }}"
    extra_args: --upgrade
  register: pip_upgrade
  when: not pip_executable_path.stat.exists

- name: Clear cache
  shell: hash -r
  changed_when: pip_upgrade is changed

- name: Install all packages with {{ pip }}
  pip:
    name: "{{ pip_install_packages }}"
    state: present
    executable: "/usr/local/bin/{{ pip }}"