---
- name: Epel repository
  yum:
    name: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ pip_epel_release }}.noarch.rpm"
    state: present
    update_cache: yes
  register: epel_repo

- name: Install pip
  yum:
    name: "{{ pip_package }}"
    state: present
  register: pip_install
  when: epel_repo.rc is defined and epel_repo.rc == 0

- name: Install all packages
  pip:
    name: "{{ pip_install_packages }}"
    state: present
  when: pip_install.rc is defined and pip_install.rc == 0